# -*- coding: utf-8 -*-
"""index.html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chpPPQL_vuXXb2rj4GGzMcpAsUhs40Ts
"""

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NEXUS TEAM - المخطط الاستراتيجي المتكامل</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;700;900&family=Orbitron:wght@400;700;900&family=Rubik+Glitch&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
    <style>
        :root {
            --primary: #00f2ff;
            --secondary: #ff003c;
            --tertiary: #7000ff;
            --bg: #030712;
            --text: #ffffff;
            --glass: rgba(15, 23, 42, 0.9);
            --glass-border: rgba(0, 242, 255, 0.2);
            --accent-gold: #ffaa00;
        }

        * { box-sizing: border-box; margin: 0; padding: 0; cursor: none !important; scroll-behavior: smooth; }

        body {
            background-color: var(--bg);
            color: var(--text);
            font-family: 'Cairo', sans-serif;
            overflow-x: hidden;
            line-height: 1.6;
        }

        /* Custom Cursor */
        .cursor-dot { width: 6px; height: 6px; background: var(--primary); position: fixed; border-radius: 50%; pointer-events: none; z-index: 9999; transform: translate(-50%, -50%); box-shadow: 0 0 10px var(--primary); }
        .cursor-ring { width: 35px; height: 35px; border: 1px solid var(--primary); position: fixed; border-radius: 50%; pointer-events: none; z-index: 9999; transform: translate(-50%, -50%); transition: width 0.1s, height 0.1s; }

        /* Navigation Sidebar */
        .nav-sidebar {
            position: fixed; left: 20px; top: 50%; transform: translateY(-50%);
            z-index: 1000; display: flex; flex-direction: column; gap: 10px;
        }
        .nav-dot {
            width: 8px; height: 8px; border: 1px solid var(--primary); border-radius: 50%;
            transition: 0.3s; position: relative; cursor: pointer !important;
        }
        .nav-dot.active { background: var(--primary); transform: scale(1.5); box-shadow: 0 0 10px var(--primary); }
        .nav-label {
            position: absolute; left: 25px; top: -5px; color: var(--primary);
            font-size: 11px; white-space: nowrap; opacity: 0; transition: 0.3s;
            font-family: 'Orbitron', sans-serif; pointer-events: none;
        }
        .nav-dot:hover .nav-label { opacity: 1; }

        /* Background Effects */
        #bg-canvas { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; opacity: 0.15; pointer-events: none; }
        .progress-bar { position: fixed; top: 0; left: 0; height: 4px; background: linear-gradient(90deg, var(--primary), var(--secondary)); width: 0%; z-index: 10001; }

        /* Layout */
        .slide {
            width: 100%; min-height: 100vh; display: flex; align-items: center; justify-content: center;
            position: relative; padding: 80px 10%; border-bottom: 1px solid rgba(255,255,255,0.05);
        }
        .content-box { width: 1100px; position: relative; z-index: 2; }

        /* Visual Media */
        .image-container {
            width: 100%; height: 400px; border-radius: 20px; margin: 30px 0;
            overflow: hidden; border: 1px solid var(--glass-border); position: relative;
            box-shadow: 0 20px 50px rgba(0,0,0,0.5);
        }
        .image-container img { width: 100%; height: 100%; object-fit: cover; transition: 1.5s ease; }
        .image-container:hover img { transform: scale(1.1); filter: brightness(1.1); }

        /* Typography */
        .glitch-title {
            font-family: 'Rubik Glitch', sans-serif; font-size: clamp(3rem, 10vw, 7rem);
            background: linear-gradient(90deg, #fff, var(--primary), var(--secondary));
            -webkit-background-clip: text; -webkit-text-fill-color: transparent; text-align: center;
            margin-bottom: 20px;
        }
        .section-header {
            font-size: 42px; color: var(--primary); margin-bottom: 30px;
            font-family: 'Orbitron', sans-serif; border-right: 6px solid var(--secondary); padding-right: 20px;
            text-shadow: 0 0 15px rgba(0, 242, 255, 0.4);
        }

        /* Elements */
        .grid-container { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 25px; margin-top: 30px; }
        .card {
            background: var(--glass); border: 1px solid var(--glass-border); padding: 35px;
            border-radius: 20px; transition: 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275); position: relative; overflow: hidden;
            backdrop-filter: blur(10px);
        }
        .card:hover { transform: translateY(-15px) scale(1.02); border-color: var(--primary); box-shadow: 0 10px 30px rgba(0, 242, 255, 0.1); }
        .card i { font-size: 40px; color: var(--primary); margin-bottom: 20px; display: block; }
        .card h3 { color: var(--secondary); margin-bottom: 15px; font-family: 'Orbitron'; font-size: 22px; letter-spacing: 1px; }
        .card p { font-size: 16px; color: #cbd5e1; }

        /* Table Style */
        .app-table {
            width: 100%; border-collapse: collapse; margin-top: 30px; background: var(--glass);
            border-radius: 15px; overflow: hidden; font-family: 'Cairo';
        }
        .app-table th, .app-table td { padding: 18px; text-align: right; border-bottom: 1px solid var(--glass-border); }
        .app-table th { background: rgba(0, 242, 255, 0.1); color: var(--primary); font-family: 'Orbitron'; font-size: 14px; }
        .app-table tr:hover { background: rgba(255, 255, 255, 0.03); }
        .tag { padding: 4px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; background: var(--secondary); }

        /* Colab Support Section */
        .code-block {
            background: #0d1117; border-radius: 10px; padding: 20px; font-family: 'Consolas', monospace;
            color: #e6edf3; border-left: 4px solid var(--primary); margin: 20px 0; font-size: 14px;
            direction: ltr; text-align: left; overflow-x: auto;
        }

        .price-tag { font-family: 'Orbitron'; color: var(--accent-gold); font-size: 28px; font-weight: bold; display: block; margin-top: 15px; }
        .reveal { opacity: 0; transform: translateY(40px); transition: all 0.8s ease-out; }
        .reveal.visible { opacity: 1; transform: translateY(0); }

        .cta-btn {
            background: linear-gradient(45deg, var(--primary), var(--tertiary)); color: #000; padding: 15px 45px; border-radius: 50px;
            font-weight: 900; text-decoration: none; display: inline-block; transition: 0.4s;
            margin-top: 30px; font-family: 'Orbitron'; letter-spacing: 2px; text-transform: uppercase;
        }
        .cta-btn:hover { box-shadow: 0 0 30px var(--primary); transform: scale(1.1); letter-spacing: 4px; }

    </style>
</head>
<body>

<div class="cursor-dot"></div>
<div class="cursor-ring"></div>
<div class="progress-bar" id="progressBar"></div>

<nav class="nav-sidebar">
    <div class="nav-dot active" data-target="s1"><span class="nav-label">01 البداية</span></div>
    <div class="nav-dot" data-target="s2"><span class="nav-label">02 الفلسفة</span></div>
    <div class="nav-dot" data-target="s3"><span class="nav-label">03 الترسانة الرقيمة</span></div>
    <div class="nav-dot" data-target="s4"><span class="nav-label">04 بيئة Colab</span></div>
    <div class="nav-dot" data-target="s5"><span class="nav-label">05 UE5 القوة</span></div>
    <div class="nav-dot" data-target="s6"><span class="nav-label">06 الهوية الرقمية</span></div>
    <div class="nav-dot" data-target="s7"><span class="nav-label">07 أدوات الإنتاج</span></div>
    <div class="nav-dot" data-target="s8"><span class="nav-label">08 الميزانية</span></div>
    <div class="nav-dot" data-target="s9"><span class="nav-label">09 السيرفرات</span></div>
    <div class="nav-dot" data-target="s10"><span class="nav-label">10 خطة التسويق</span></div>
    <div class="nav-dot" data-target="s11"><span class="nav-label">11 ذكاء Gemini</span></div>
    <div class="nav-dot" data-target="s12"><span class="nav-label">12 الاستثمار</span></div>
    <div class="nav-dot" data-target="s13"><span class="nav-label">13 عالم اللعبة</span></div>
    <div class="nav-dot" data-target="s14"><span class="nav-label">14 الميكانيكا</span></div>
    <div class="nav-dot" data-target="s15"><span class="nav-label">15 المجتمع</span></div>
    <div class="nav-dot" data-target="s16"><span class="nav-label">16 خارطة الطريق</span></div>
    <div class="nav-dot" data-target="s17"><span class="nav-label">17 الأرباح</span></div>
    <div class="nav-dot" data-target="s18"><span class="nav-label">18 الشركاء</span></div>
    <div class="nav-dot" data-target="s19"><span class="nav-label">19 الرؤية</span></div>
    <div class="nav-dot" data-target="s20"><span class="nav-label">20 الختام</span></div>
</nav>

<canvas id="bg-canvas"></canvas>

<div class="presentation-wrapper">

    <!-- 1. Hero -->
    <section class="slide" id="s1">
        <div class="content-box" style="text-align: center;">
            <div class="reveal">
                <h1 class="glitch-title">NEXUS NEXGEN</h1>
                <div class="image-container">
                    <img src="https://images.unsplash.com/photo-1614850523296-e8c1d4766044?auto=format&fit=crop&q=80&w=1200" alt="Cyberpunk World">
                </div>
                <p style="font-size: 24px; color: var(--primary); font-family: 'Orbitron'; font-weight: 700;">التطور القادم في تطوير الألعاب المستقلة</p>
                <p style="margin-top: 15px; color: #aaa; max-width: 800px; margin-inline: auto;">نحن لا نبني مجرد ألعاب، نحن نبني عوالم رقمية تتجاوز حدود الخيال. بدمج العتاد الشخصي القوي مع تقنيات السحاب والذكاء الاصطناعي، نخلق تجربة لا تُنسى.</p>
            </div>
        </div>
    </section>

    <!-- 2. Concept Deep Dive -->
    <section class="slide" id="s2">
        <div class="content-box">
            <h2 class="section-header reveal">فلسفة التيم اللامركزي</h2>
            <div class="grid-container">
                <div class="card reveal">
                    <i class="fas fa-brain"></i>
                    <h3>الاستثمار في العقل</h3>
                    <p>بدلاً من إهدار الميزانية في تأثيث المكاتب، نوجه كل دولار لتطوير الأنظمة، شراء الأصول الرقمية النادرة، وتدريب الفريق على أحدث تقنيات المحركات.</p>
                </div>
                <div class="card reveal">
                    <i class="fas fa-bolt"></i>
                    <h3>السرعة والرشاقة</h3>
                    <p>فريقنا يعمل بنظام "الكتيبة الرقمية"؛ كل فرد لديه استوديو متكامل في منزله، مما يلغي البيروقراطية ويجعل عملية التطوير أسرع بنسبة 40%.</p>
                </div>
            </div>
            <div class="image-container reveal" style="height: 300px;">
                <img src="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1000" alt="Cyber Security">
            </div>
        </div>
    </section>

    <!-- 3. Tools Table -->
    <section class="slide" id="s3">
        <div class="content-box">
            <h2 class="section-header reveal">ترسانة التطبيقات البرمجية</h2>
            <div class="reveal">
                <table class="app-table">
                    <thead>
                        <tr>
                            <th>التطبيق</th>
                            <th>الاستخدام الرئيسي</th>
                            <th>الحالة</th>
                            <th>المنصة</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Unreal Engine 5.4</td>
                            <td>تطوير البيئات، الإضاءة، والبرمجة المرئية Blueprints.</td>
                            <td><span class="tag">أساسي</span></td>
                            <td>Windows</td>
                        </tr>
                        <tr>
                            <td>Substance Painter</td>
                            <td>تصميم الأنسجة (Textures) والخرائط الواقعية للمجسمات.</td>
                            <td><span class="tag">إبداعي</span></td>
                            <td>Windows</td>
                        </tr>
                        <tr>
                            <td>Google Colab</td>
                            <td>تدريب نماذج الذكاء الاصطناعي ومعالجة البيانات الضخمة.</td>
                            <td><span class="tag">سحابي</span></td>
                            <td>Web / Python</td>
                        </tr>
                        <tr>
                            <td>Blender 4.0</td>
                            <td>النمذجة ثلاثية الأبعاد، الأنيميشن، وتصدير الأصول.</td>
                            <td><span class="tag">مجاني</span></td>
                            <td>Cross-Platform</td>
                        </tr>
                        <tr>
                            <td>Discord HQ</td>
                            <td>التواصل الفوري، مشاركة الشاشة، واجتماعات الـ Sprint.</td>
                            <td><span class="tag">تواصل</span></td>
                            <td>Mobile/PC</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <!-- 4. Google Colab Support -->
    <section class="slide" id="s4">
        <div class="content-box">
            <h2 class="section-header reveal">بيئة البرمجة السحابية (Colab)</h2>
            <p class="reveal">ندمج أكواد Python المتقدمة لتحليل سلوك اللاعبين وتوليد الشخصيات آلياً. يمكنك تشغيل هذا الكود مباشرة في Google Colab للتحكم في سيرفراتنا:</p>
            <div class="code-block reveal">
# Nexus AI Engine Connection Script
import google.colab as colab
import requests

def connect_to_nexus_core(api_key):
    print("Connecting to Nexus Dev Servers...")
    # Logic for model training
    endpoint = f"https://api.nexus-team.dev/v1/train?key={api_key}"
    response = {"status": "success", "engine": "UE5-Link-Active"}
    return response

# Initialize Connection
status = connect_to_nexus_core("NEX-99-BETA")
print(f"Server Status: {status['status']} | Engine: {status['engine']}")
            </div>
            <div class="image-container reveal" style="height: 250px;">
                <img src="https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=1000" alt="Code Screen">
            </div>
        </div>
    </section>

    <!-- 5. Unreal Engine Power -->
    <section class="slide" id="s5">
        <div class="content-box">
            <h2 class="section-header reveal">قوة المحرك الخامس</h2>
            <div class="image-container reveal">
                <img src="https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=1200" alt="Unreal Engine Visualization">
            </div>
            <p class="reveal">نحن لا نكتفي بالرسم، بل نستخدم تقنية **Nanite** لعرض مليارات المضلعات في الوقت الحقيقي، و **Lumen** لتوفير إضاءة عالمية تحاكي الواقع بدقة مذهلة، مما يمنح لعبتنا مظهراً يتفوق على ألعاب الـ AAA بميزانية أقل.</p>
        </div>
    </section>

    <!-- 6. Brand Identity -->
    <section class="slide" id="s6">
        <div class="content-box">
            <h2 class="section-header reveal">الهوية الرقمية الموحدة</h2>
            <div class="grid-container">
                <div class="card reveal">
                    <h3>التصميم البصري</h3>
                    <p>نعتمد لغة بصرية تمزج بين "سايبربانك" والنيون العربي، لخلق هوية فريدة في سوق الألعاب العالمي.</p>
                </div>
                <div class="card reveal" style="border-color: var(--secondary);">
                    <h3>شعار الفريق</h3>
                    <p>يمثل التداخل الرقمي والذكاء الاصطناعي، مصمم ليكون قابلاً للتوسع في الميتافيرس.</p>
                </div>
            </div>
            <div class="image-container reveal" style="height: 300px;">
                <img src="https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1000" alt="Cyber Identity">
            </div>
        </div>
    </section>

    <!-- 7. Production Assets -->
    <section class="slide" id="s7">
        <div class="content-box">
            <h2 class="section-header reveal">أدوات الإنتاج المتقدمة</h2>
            <div class="grid-container">
                <div class="card reveal">
                    <i class="fas fa-walking"></i>
                    <h3>Xsens Mocap</h3>
                    <p>بدلات التقاط حركة متطورة تغنينا عن التحريك اليدوي الممل، وتجعل حركات القتال والمشي تبدو طبيعية تماماً.</p>
                </div>
                <div class="card reveal">
                    <i class="fas fa-vr-cardboard"></i>
                    <h3>Spatial Computing</h3>
                    <p>استخدام نظارات الواقع المختلط لاختبار تجربة اللاعب من منظور الشخص الأول والثالث بشكل مباشر.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- 8. Detailed Budget -->
    <section class="slide" id="s8">
        <div class="content-box">
            <h2 class="section-header reveal">توزيع الميزانية الذكية</h2>
            <div class="grid-container">
                <div class="card reveal">
                    <h3>أصول Quixel</h3>
                    <span class="price-tag">$4,500</span>
                    <p>ترخيص المكتبة الكاملة للمسح التصويري الواقعي.</p>
                </div>
                <div class="card reveal">
                    <h3>تراخيص Maya/Adobe</h3>
                    <span class="price-tag">$3,000</span>
                    <p>اشتراكات سنوية لكامل أعضاء الفريق الإبداعي.</p>
                </div>
                <div class="card reveal">
                    <h3>صوتيات 3D</h3>
                    <span class="price-tag">$2,500</span>
                    <p>مكتبات صوتية محيطية Dolby Atmos.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- 9. Global Infrastructure -->
    <section class="slide" id="s9">
        <div class="content-box">
            <h2 class="section-header reveal">البنية التحتية العالمية</h2>
            <p class="reveal">نعتمد على تقنيات AWS و Azure لتوفير تجربة "أونلاين" بدون تأخير (Ping منخفض)، مما يضمن استجابة سريعة للاعبين في منطقة الشرق الأوسط وشمال أفريقيا.</p>
            <div class="image-container reveal">
                <img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc51?auto=format&fit=crop&q=80&w=1200" alt="Server Infrastructure">
            </div>
        </div>
    </section>

    <!-- 10. Marketing Blitz -->
    <section class="slide" id="s10">
        <div class="content-box">
            <h2 class="section-header reveal">استراتيجية التسويق الهجومي</h2>
            <div class="card reveal">
                <p>سنعتمد على "صدمة الجودة"؛ نشر مقاطع فيديو بدقة 4K تظهر رسوميات لا يصدق الجمهور أنها من إنتاج فريق مستقل، مع التركيز على التعاون مع كبار صناع المحتوى في Twitch.</p>
                <span class="price-tag">ميزانية الحملة: $15,000</span>
            </div>
            <div class="image-container reveal" style="height: 300px;">
                <img src="https://images.unsplash.com/photo-1551288049-bbbda546697a?auto=format&fit=crop&q=80&w=1000" alt="Data Analytics">
            </div>
        </div>
    </section>

    <!-- 11. AI Core (Gemini) -->
    <section class="slide" id="s11">
        <div class="content-box">
            <h2 class="section-header reveal">التفاعل بذكاء Gemini</h2>
            <div class="grid-container">
                <div class="card reveal">
                    <i class="fas fa-comments"></i>
                    <h3>حوارات بلا حدود</h3>
                    <p>كل شخصية في لعبتنا تمتلك "دماغاً" متصلاً بـ Gemini، مما يتيح لك التحدث معهم بحرية وسيغيرون ردود فعلهم بناءً على أسلوبك.</p>
                </div>
                <div class="card reveal">
                    <i class="fas fa-map"></i>
                    <h3>توليد عوالم</h3>
                    <p>الذكاء الاصطناعي يقوم ببناء القرى والمهمات الجانبية بشكل فريد لكل لاعب.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- 12. Investment Value -->
    <section class="slide" id="s12">
        <div class="content-box" style="text-align: center;">
            <h2 class="section-header reveal">لماذا نحن؟ (القيمة الاستثمارية)</h2>
            <div class="reveal">
                <span class="glitch-title" style="font-size: 80px; color: var(--accent-gold);">$30,000</span>
                <p style="font-size: 20px;">هذه الميزانية قادرة على إنتاج ديمو (Demo) يضاهي مشاريع كلفتها الملايين، لأننا نمتلك المعرفة والعتاد مسبقاً.</p>
            </div>
        </div>
    </section>

    <!-- 13. The World -->
    <section class="slide" id="s13">
        <div class="content-box">
            <h2 class="section-header reveal">عالم "Shadow Protocol"</h2>
            <div class="image-container reveal">
                <img src="https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&q=80&w=1200" alt="Future City">
            </div>
            <p class="reveal">تقع أحداث اللعبة في مدينة "نيوم-2099"، حيث تتصارع الشركات الكبرى على موارد الطاقة. أنت تلعب دور "المهندس الشبح" الذي يمتلك القدرة على اختراق أي نظام إلكتروني بمجرد النظر إليه.</p>
        </div>
    </section>

    <!-- 14. Mechanics -->
    <section class="slide" id="s14">
        <div class="content-box">
            <h2 class="section-header reveal">ميكانيكا اللعب المبتكرة</h2>
            <div class="grid-container">
                <div class="card reveal"><h3>الباركور التقني</h3><p>حركات انسيابية على الجدران والأسقف باستخدام مغناطيسية الأطراف.</p></div>
                <div class="card reveal"><h3>الزمن المتوقف</h3><p>إمكانية إيقاف الزمن لمدة 3 ثوانٍ لإعادة برمجة طلقات العدو.</p></div>
            </div>
        </div>
    </section>

    <!-- 15. Social Sync -->
    <section class="slide" id="s15">
        <div class="content-box">
            <h2 class="section-header reveal">الارتباط بالمجتمع</h2>
            <p class="reveal">سنقوم ببناء أول استوديو "شفاف"؛ حيث يمكن للاعبين الدخول إلى ديسكورد ومشاهدة عمليات التطوير والبث المباشر للبرمجة، والمشاركة في اتخاذ قرارات تصميم الشخصيات.</p>
            <div class="image-container reveal" style="height: 300px;">
                <img src="https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=1000" alt="Gamers Community">
            </div>
        </div>
    </section>

    <!-- 16. The Roadmap -->
    <section class="slide" id="s16">
        <div class="content-box">
            <h2 class="section-header reveal">خارطة الطريق (2024-2025)</h2>
            <div class="grid-container">
                <div class="card reveal"><h3>الربع الأول</h3><p>بناء الميكانيكا الأساسية ونظام الذكاء الاصطناعي.</p></div>
                <div class="card reveal"><h3>الربع الثاني</h3><p>إطلاق النسخة التجريبية (Vertical Slice) للمستثمرين.</p></div>
            </div>
        </div>
    </section>

    <!-- 17. Revenue Model -->
    <section class="slide" id="s17">
        <div class="content-box">
            <h2 class="section-header reveal">نموذج الإيرادات المستدام</h2>
            <div class="card reveal">
                <p>1. مبيعات اللعبة على Steam و Epic Store.<br>2. بيع الأصول البرمجية التي نطورها في متجر Unreal Marketplace كدخل جانبي للفريق.</p>
            </div>
        </div>
    </section>

    <!-- 18. Partners -->
    <section class="slide" id="s18">
        <div class="content-box">
            <h2 class="section-header reveal">شركاء النجاح التقني</h2>
            <p class="reveal">نحن نسعى للحصول على دعم Nvidia Inception لدعمنا بوحدات معالجة الرسوميات السحابية، و Unreal MegaGrants لدعم التمويل بدون مقابل حصص.</p>
        </div>
    </section>

    <!-- 19. The Vision -->
    <section class="slide" id="s19">
        <div class="content-box">
            <h2 class="section-header reveal">رؤية "نيكسوس" للعام القادم</h2>
            <div class="image-container reveal">
                <img src="https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200" alt="Global Connectivity">
            </div>
            <p class="reveal">رؤيتنا هي بناء "محرك إبداعي" وليس فقط استوديو، حيث يمكن لأي موهبة عربية الانضمام إلينا من أي مكان في العالم والمساهمة في صناعة ألعاب تنافس عالمياً.</p>
        </div>
    </section>

    <!-- 20. Call to Action -->
    <section class="slide" id="s20">
        <div class="content-box" style="text-align: center;">
            <div class="reveal">
                <h2 class="glitch-title">اصنع المستقبل معنا</h2>
                <p style="font-size: 20px; color: var(--primary);">المستقبل لا يُنتظر، بل يُبنى بالكود والإبداع.</p>
                <a href="#" class="cta-btn">ابدأ رحلتك كشريك</a>
            </div>
        </div>
    </section>

</div>

<script>
    // --- Cursor Logic ---
    const cursorDot = document.querySelector('.cursor-dot');
    const cursorRing = document.querySelector('.cursor-ring');
    document.addEventListener('mousemove', (e) => {
        cursorDot.style.left = e.clientX + 'px';
        cursorDot.style.top = e.clientY + 'px';
        gsap.to(cursorRing, { x: e.clientX, y: e.clientY, duration: 0.1 });
    });

    // --- Background Animation (Enhanced) ---
    const canvas = document.getElementById('bg-canvas');
    const ctx = canvas.getContext('2d');
    let particles = [];
    function initCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        particles = [];
        for(let i=0; i<80; i++) particles.push({
            x: Math.random()*canvas.width,
            y: Math.random()*canvas.height,
            vx: (Math.random()-0.5)*0.3,
            vy: (Math.random()-0.5)*0.3,
            size: Math.random()*2
        });
    }
    function animate() {
        ctx.clearRect(0,0,canvas.width,canvas.height);
        ctx.fillStyle = '#00f2ff';
        particles.forEach(p => {
            p.x += p.vx; p.y += p.vy;
            if(p.x<0 || p.x>canvas.width) p.vx *= -1;
            if(p.y<0 || p.y>canvas.height) p.vy *= -1;
            ctx.beginPath(); ctx.arc(p.x, p.y, p.size, 0, Math.PI*2); ctx.fill();
        });
        requestAnimationFrame(animate);
    }
    window.addEventListener('resize', initCanvas);
    initCanvas(); animate();

    // --- GSAP Scroll Logic ---
    gsap.registerPlugin(ScrollTrigger);

    gsap.to("#progressBar", {
        width: "100%",
        scrollTrigger: { scrub: 0.2 }
    });

    // Enhanced Reveal Logic
    const reveals = gsap.utils.toArray('.reveal');
    reveals.forEach(el => {
        gsap.to(el, {
            scrollTrigger: {
                trigger: el,
                start: "top 85%",
                onEnter: () => el.classList.add('visible')
            }
        });
    });

    // Nav Dot Update
    const dots = document.querySelectorAll('.nav-dot');
    const sections = document.querySelectorAll('.slide');

    window.addEventListener('scroll', () => {
        let current = "";
        sections.forEach(s => {
            const sectionTop = s.offsetTop;
            if(pageYOffset >= sectionTop - 400) current = s.id;
        });
        dots.forEach(d => {
            d.classList.remove('active');
            if(d.dataset.target === current) d.classList.add('active');
        });
    });

    dots.forEach(d => {
        d.onclick = () => {
            const target = document.getElementById(d.dataset.target);
            window.scrollTo({
                top: target.offsetTop,
                behavior: 'smooth'
            });
        };
    });

</script>

</body>
</html>